Location: AbstractExceptionTest.java

Content: 

protected Exception generateCause(){

  return new Exception(CAUSE_MESSAGE);

}

